### PR TITLE
Show nicer message when Appwrite project can't be found

### LINKED ISSUE #12: Cannot use 'in' operator to search for 'data' in undefined when Appwrite instance is off
Issue Type: <b>Bug</b>

Porbably a message like: `Can't connect to your Appwrite instance` would give a better DX.

Extension version: 0.0.6
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 01de3187-d225-4927-87db-8d77c8f31a07|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #12

@eldadfux feel free to verify this is working properly for you. It should show this message when it can't connect to the Appwrite project:

image

### CODE REVIEW

**Comment by eldadfux** [comment]
Looks good from the screenshot, is there any easy way to test the extension from this specific branch?

**Comment by alexweininger** [comment]
I’ll work on setting that up now.

**Comment by alexweininger** [comment]
I've setup a Azure pipeline to build, package, then upload the extension .vsix to Azure DevOps so we can more easily test in the future.

[Link to download extension .vsix for this PR](https://dev.azure.com/streamlux/_apis/resources/Containers/15505372/vsix?itemPath=vsix%2Fvscode-appwrite-0.0.6.vsix)

[How to install extension from .vsix](https://code.visualstudio.com/docs/editor/extension-marketplace#:~:text=Install%20from%20a%20VSIX%23&text=Using%20the%20Install%20from%20VSIX,vsix%20file.)

**Comment by eldadfux** [comment]
@alexweininger I'm not authorized to access the file on Azure.

**Comment by alexweininger** [comment]
Alright I'll have to figure out a better way to upload the build artifacts in the future. For now I'll merge this anyway.

**Pull request merged**
